### ISSUE TITLE
Support more validation actions for policy bindings

### ISSUE THREAD

**Issue by f1ames** [kubeshop/monokle-admission-controller#10]
In the first version of Monokle Admission Controller, the only validation action supported is `Warn` (send warning for every policy violation detected).

```yaml
apiVersion: monokle.io/v1alpha1
kind: MonoklePolicyBinding
metadata:
  name: my-policy-binding
spec:
  policyName: my-policy
  validationActions: [Warn]
```

We would like to expand this with more options like:
- `Ignore` - ignore violations.
- `Report` - send violation details to Monokle Cloud.
- `Deny` - block resource creation/update.

Also it could be useful to allow defined action per rule level (so different actions for warnings and errors).
