### ISSUE TITLE
Add deny action to admission controller

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle-admission-controller#20]
The admission controller currently only supports Warn which we need to improve upon for it to become truly useful. The `validationActions` could be extended with `Deny` to work consistent with [the VAP docs](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/). This works well when the rules are configured as booleans, however, when you use the "warning" or "error" level it conflicts and is confusing. Let's consider alternatives to make our product intuitive to use. 

```
apiVersion: monokle.io/v1alpha1
kind: MonoklePolicy
metadata:
  name: my-policy
spec:
  plugins:
    practices: true
  rules:
    practices/no-latest-image: err # as opposed to `true` or `false`
---
apiVersion: monokle.io/v1alpha1
kind: MonoklePolicyBinding
metadata:
  name: my-policy-binding
spec:
  policyName: my-policy
  validationActions: [Warn]
```

ps: The README has no example with a policy that overrides rules, maybe let's add one in to showcase that you can do more then enable/disable plugins

**Comment by olensmar** [comment]
good catch @WitoDelnat !

**Comment by WitoDelnat** [comment]
Some brainstorming

- Omit validationActions and perform actions based on the level (i.e. errors will Deny and warnings will Warn). The downside is that no other actions can be added
- Maybe use `warnActions` and `errorActions` instead, but this feels a bit odd.
- Maybe use other values for validationAction: `DenyOnError`, `DenyOnWarning`, `WarnOnError` it gets a bit weird for `WarnOnWarning` but could be fine? We could even keep `Deny` as alias for `DenyOnError` and Warn as alias for `WarnOnError + WarnOnWarning`.

**Comment by f1ames** [comment]
Support for `Deny` action was introduced in https://github.com/kubeshop/monokle-admission-controller/pull/14. But it uses `validationActions` as VAP so doesn't solve `warn/err` confusion. And also this is not yet configurable on the Cloud so this is something to have in mind (as we probably should work on this soon).

> * Omit validationActions and perform actions based on the level (i.e. errors will Deny and warnings will Warn). The downside is that no other actions can be added

That could solve this and we get integration with Cloud for free - I mean controlling the action based on what is set in Monokle Cloud (warn or err).

> * Maybe use `warnActions` and `errorActions` instead, but this feels a bit odd.
> * Maybe use other values for validationAction: `DenyOnError`, `DenyOnWarning`, `WarnOnError` it gets a bit weird for `WarnOnWarning` but could be fine? We could even keep `Deny` as alias for `DenyOnError` and Warn as alias for `WarnOnError + WarnOnWarning` i.e. `WarnOnAny`.

How about deviating a bit from VAP `validationActions` making it nested config like:

```yaml
apiVersion: monokle.io/v1alpha1
kind: MonoklePolicyBinding
metadata:
  name: my-policy-binding
spec:
  policyName: my-policy
  validationActions:
    onWarn: [Warn, Audit]
    onErr: [Deny, Audit]
```

we can even make it VAP-compatible also allowing shorthand version (actions applied for all rules then) as we have now:

```yaml
apiVersion: monokle.io/v1alpha1
kind: MonoklePolicyBinding
metadata:
  name: my-policy-binding
spec:
  policyName: my-policy
  validationActions: [Warn, Audit]
```

---

Related also to https://github.com/kubeshop/monokle-admission-controller/issues/10.

**Comment by WitoDelnat** [comment]
I like your suggestion of having a nested object. You can also fine-grained set what you want to report to Monokle Cloud which will be neat! I've been thinking more about it and I'd refrain from shorthand `Warn | Deny` as they will all simply be confusing and give undesired behaviour. 

So my vote is for sensible defaults to make `validationActions` optional together with this extended format for tweaking it. 

```
apiVersion: monokle.io/v1alpha1
kind: MonoklePolicyBinding
metadata:
  name: my-policy-binding
spec:
  policyName: my-policy
  validationActions:
    onWarn: [Warn, Audit]
    onErr: [Deny, Audit]
```
